// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDME2uKnon9m-g2QuNbp3ryXLr_dmDPeaY',
    appId: '1:107248329794:web:6d75533a155b7c2bf8b9db',
    messagingSenderId: '107248329794',
    projectId: 'sachat-98299',
    authDomain: 'sachat-98299.firebaseapp.com',
    storageBucket: 'sachat-98299.appspot.com',
    measurementId: 'G-EBW37YP4N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmmWn14mz9UA_rSPyavRDN4Xe2V8UKMvE',
    appId: '1:107248329794:android:f6eb987b7514a42cf8b9db',
    messagingSenderId: '107248329794',
    projectId: 'sachat-98299',
    storageBucket: 'sachat-98299.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp068P9Ny1857TYyrtOqA9eki-Suam7es',
    appId: '1:107248329794:ios:9ab947c0471bbd69f8b9db',
    messagingSenderId: '107248329794',
    projectId: 'sachat-98299',
    storageBucket: 'sachat-98299.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp068P9Ny1857TYyrtOqA9eki-Suam7es',
    appId: '1:107248329794:ios:69c92be231a46bc9f8b9db',
    messagingSenderId: '107248329794',
    projectId: 'sachat-98299',
    storageBucket: 'sachat-98299.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
